imports:
    - { resource: "@ArtesanikSyliusEmployeePlugin/Resources/config/resources.yml" }
    - { resource: "@ArtesanikSyliusEmployeePlugin/Resources/config/services.yml" }
    - { resource: "@ArtesanikSyliusEmployeePlugin/Resources/config/grids.yml" }