sylius_customer:
    resources:
        customer:
            classes: 
                model: Artesanik\SyliusEmployeePlugin\Entity\Customer\Customer
                repository: Artesanik\SyliusEmployeePlugin\Repository\CustomerRepository
sylius_order:
    resources:
        order:
            classes:
                repository: Artesanik\SyliusEmployeePlugin\Repository\OrderRepository
sylius_resource:
    resources:
        artesanik_sylius_employee.limit:
            classes:
                model: Artesanik\SyliusEmployeePlugin\Entity\Employee\Limit
                form: Artesanik\SyliusEmployeePlugin\Form\Type\EmployeeLimitType
                repository: Artesanik\SyliusEmployeePlugin\Repository\Employee\LimitRepository
        artesanik_sylius_employee.mapping:
            classes:
                model: Artesanik\SyliusEmployeePlugin\Entity\Customer\Customer
                repository: Artesanik\SyliusEmployeePlugin\Repository\CustomerRepository
        artesanik_sylius_employee.assign:
            classes:
                model: Artesanik\SyliusEmployeePlugin\Entity\Customer\Customer
                repository: Artesanik\SyliusEmployeePlugin\Repository\CustomerRepository
sylius_ui:
    events:
        sylius.admin.customer.create.form:
            blocks:
                customer_employee_information_fields: '@ArtesanikSyliusEmployeePlugin/Resources/views/Customer/Form/Employee/_form.html.twig'
        sylius.admin.customer.show.address:
            blocks:
                customer_limit_information_summary: '@ArtesanikSyliusEmployeePlugin/Resources/views/Customer/Show/Employee/_summary.html.twig'
                customer_employee_information_header: '@ArtesanikSyliusEmployeePlugin/Resources/views/Customer/Show/Employee/_header.html.twig'
                customer_employee_information_details: '@ArtesanikSyliusEmployeePlugin/Resources/views/Customer/Show/Employee/_content.html.twig'
        sylius.shop.account.dashboard.after_information:
            blocks:
                customer_employee_information_account: '@ArtesanikSyliusEmployeePlugin/Resources/views/Account/_employee_information.html.twig'
        sylius.shop.layout.header:
            blocks:
                customer_limit_shop_information_header_label: '@ArtesanikSyliusEmployeePlugin/Resources/views/Shop/Header/_limitStatistics.html.twig'

